source "https://rubygems.org"

# gem 'pry'
# gem 'require_all'
# gem 'rest-client'
# gem 'mailjet'
# gem 'dotenv'
gem "sinatra-activerecord"
gem "sqlite3"
gem "pry"
gem "require_all"
gem "rake"
gem 'rest-client'
gem 'json'
gem 'dotenv'
gem 'mailjet'
